In [1]:
import pandas as pd

In [2]:
from micom.workflows import GrowthResults

first step 
- find the most abundant taxa (the taxa with more than 1% relative abundance)

In [3]:
annotations = pd.read_csv("/proj/gibbons/sswegle_micom/Res_Saves/annotations_swegle.csv")
exchanges = pd.read_csv("/proj/gibbons/sswegle_micom/Res_Saves/exchanges_swegle.csv")
growth_rates = pd.read_csv("/proj/gibbons/sswegle_micom/Res_Saves/growth_rates_swegle.csv")
growth_rates = pd.read_csv("/proj/gibbons/sswegle_micom/Res_Saves/growth_rates_swegle.csv")
res = GrowthResults(growth_rates, exchanges, annotations)

In [4]:
exchanges

,Unnamed: 0,taxon,sample_id,tolerance,reaction,flux,abundance,metabolite,direction
0,2,Alistipes,SRR15032086,0.000001,EX_h(e),-89.997588,0.120313,h[e],import
1,9,Alistipes,SRR15032086,0.000001,EX_malt(e),-0.024506,0.120313,malt[e],import
2,10,Alistipes,SRR15032086,0.000001,EX_pi(e),70.317187,0.120313,pi[e],export
3,17,Alistipes,SRR15032086,0.000001,EX_gly(e),-32.664068,0.120313,gly[e],import
4,26,Alistipes,SRR15032086,0.000001,EX_ade(e),11.025896,0.120313,ade[e],export
...,...,...,...,...,...,...,...,...,...
648745,3058276,Veillonella,SRR15032514,0.000001,EX_succ(e),169.919386,0.001058,succ[e],export
648746,3058278,Veillonella,SRR15032514,0.000001,EX_metsox_S_L(e),-0.000146,0.001058,metsox_S_L[e],import
648747,3058282,Veillonella,SRR15032514,0.000001,EX_pyr(e),-31.651654,0.001058,pyr[e],import
648748,3058288,Veillonella,SRR15032514,0.000001,EX_isoprene(e),5.508882,0.001058,ispre[e],export
648749,3058289,Veillonella,SRR15032514,0.000001,EX_oaa(e),4.876942,0.001058,oaa[e],export

next step = find the average abundance of each microbe across samples

In [5]:
grouped_microbes = exchanges.groupby(['taxon'])

In [6]:
grouped_means = grouped_microbes['abundance'].mean()

In [7]:
grouped_means

taxon
Acidaminococcus     0.011517
Actinomyces         0.000621
Adlercreutzia       0.001168
Akkermansia         0.058139
Alistipes           0.075543
                      ...
Terrisporobacter    0.014781
Varibaculum         0.006495
Veillonella         0.004449
Weissella           0.004379
medium                   NaN
Name: abundance, Length: 85, dtype: float64

In [8]:
ten_most_abundant_taxa = grouped_means.nlargest(10)
ten_most_abundant_taxa

taxon
Bacteroides         0.302967
Prevotella          0.124266
Faecalibacterium    0.107079
Roseburia           0.087074
Blautia             0.082805
Alistipes           0.075543
Ruminococcus        0.058961
Akkermansia         0.058139
Paraprevotella      0.045048
Megamonas           0.033435
Name: abundance, dtype: float64

- this shows the ten most abundant microbes in my sample 
- but, needs to be in table format again

In [9]:
only_top_ten = growth_rates.loc[growth_rates['abundance'] >= .035445]
only_top_ten

,compartments,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id
1,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081
2,Alistipes,0.064537,0.210478,2650,1613,Alistipes,0.7,SRR15032081
3,Bacteroides,0.203834,0.506204,3293,1883,Bacteroides,0.7,SRR15032081
5,Blautia,0.129073,0.262992,2808,1732,Blautia,0.7,SRR15032081
6,Eubacterium,0.051118,0.101162,2073,1577,Eubacterium,0.7,SRR15032081
...,...,...,...,...,...,...,...,...
6294,Blautia,0.105515,0.203996,2808,1732,Blautia,0.7,SRR15032514
6296,Coprococcus,0.093003,0.179806,2188,1591,Coprococcus,0.7,SRR15032514
6301,Faecalibacterium,0.133591,0.258274,1986,1472,Faecalibacterium,0.7,SRR15032514
6307,Roseburia,0.087276,0.168734,2357,1567,Roseburia,0.7,SRR15032514
6308,Ruminococcus,0.038845,0.075099,2779,1788,Ruminococcus,0.7,SRR15032514

In [10]:
metadata = pd.read_csv("/proj/gibbons/sswegle_micom/All the Steps/metadata_swegle.csv")
metadata

,Unnamed: 0,sample_id,description,time_point,file,found_taxa,total_taxa,found_fraction,found_abundance_fraction,medium
0,0,SRR15032078,High fiber diet,8,SRR15032078.pickle,24.0,37.0,0.648649,0.889586,high_fiber
1,1,SRR15032079,High fiber diet,4,SRR15032079.pickle,21.0,25.0,0.840000,0.942212,high_fiber
2,2,SRR15032080,High fermented food diet,3,SRR15032080.pickle,16.0,27.0,0.592593,0.855661,fermented
3,3,SRR15032081,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
4,4,SRR15032082,High fiber diet,7,SRR15032082.pickle,23.0,33.0,0.696970,0.908204,high_fiber
...,...,...,...,...,...,...,...,...,...,...
306,306,SRR15032510,High fermented food diet,2,SRR15032510.pickle,21.0,28.0,0.750000,0.881483,western
307,307,SRR15032511,High fiber diet,6,SRR15032511.pickle,22.0,32.0,0.687500,0.799526,high_fiber
308,308,SRR15032512,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented
309,309,SRR15032513,High fermented food diet,6,SRR15032513.pickle,19.0,30.0,0.633333,0.839063,fermented
310,310,SRR15032514,High fiber diet,9,SRR15032514.pickle,24.0,37.0,0.648649,0.740106,western

In [11]:
filtered_meta = metadata[metadata.time_point < 8]

In [12]:
top_ten_merged = only_top_ten.merge(filtered_meta, on="sample_id")

In [13]:
top_ten_merged

,compartments,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id,Unnamed: 0,description,time_point,file,found_taxa,total_taxa,found_fraction,found_abundance_fraction,medium
0,Akkermansia,0.133546,7.736626e-02,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
1,Alistipes,0.064537,2.104784e-01,2650,1613,Alistipes,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
2,Bacteroides,0.203834,5.062036e-01,3293,1883,Bacteroides,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
3,Blautia,0.129073,2.629917e-01,2808,1732,Blautia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
4,Eubacterium,0.051118,1.011622e-01,2073,1577,Eubacterium,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1788,Anaerostipes,0.047938,1.497117e-02,2034,1491,Anaerostipes,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented
1789,Bacteroides,0.488549,3.029477e-01,3293,1883,Bacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented
1790,Blautia,0.094856,3.214070e-06,2808,1732,Blautia,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented
1791,Faecalibacterium,0.120583,3.149052e-11,1986,1472,Faecalibacterium,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented
1792,Parabacteroides,0.057953,6.170115e-02,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented

In [14]:
#merged.rename(columns={"compartments": "taxon"}, inplace=True)
#merged
small_ex = exchanges[['taxon', 'sample_id', 'direction', 'metabolite', 'flux']]

In [15]:
merged_including_direction_and_metabolite = pd.merge(top_ten_merged, small_ex, how="left", left_on= ['taxon', 'sample_id'], right_on = ['taxon', 'sample_id'])
merged_including_direction_and_metabolite

,compartments,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id,Unnamed: 0,description,time_point,file,found_taxa,total_taxa,found_fraction,found_abundance_fraction,medium,direction,metabolite,flux
0,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,export,MGlcn148[e],0.000002
1,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,export,h[e],149.145825
2,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,export,MGlcn46[e],0.000003
3,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,export,MGlcn23_rl[e],0.000001
4,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,export,MGlcn59[e],0.000002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184977,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,pydxn[e],-0.000189
184978,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,ura[e],-22.903380
184979,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,export,etoh[e],10.690341
184980,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,fe3[e],-0.000499
184981,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,export,succ[e],8.352195

In [16]:
only_imports = merged_including_direction_and_metabolite.loc[merged_including_direction_and_metabolite.direction == 'import']
only_imports

,compartments,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id,Unnamed: 0,description,time_point,file,found_taxa,total_taxa,found_fraction,found_abundance_fraction,medium,direction,metabolite,flux
5,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,import,MGlcn144[e],-0.000001
6,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,import,MGlcn68_rl[e],-0.000001
7,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,import,pi[e],-0.137294
8,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,import,acnam[e],-5.706658
10,Akkermansia,0.133546,0.077366,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,2,SRR15032081.pickle,11.0,17.0,0.647059,0.898909,western,import,gly[e],-40.258076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184975,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,met_L[e],-22.584343
184976,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,sheme[e],-0.000072
184977,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,pydxn[e],-0.000189
184978,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,ura[e],-22.903380
184980,Parabacteroides,0.057953,0.061701,2879,1747,Parabacteroides,0.7,SRR15032512,308,High fermented food diet,7,SRR15032512.pickle,23.0,37.0,0.621622,0.843232,fermented,import,fe3[e],-0.000499

In [17]:
annotations = pd.read_csv("/proj/gibbons/sswegle_micom/Res_Saves/annotations_swegle.csv")

In [18]:
merged_with_annotations = only_imports.merge(annotations, on="metabolite")

In [19]:
merged_with_annotations.columns

Index(['compartments', 'abundance', 'growth_rate', 'reactions', 'metabolites',
       'taxon', 'tradeoff', 'sample_id', 'Unnamed: 0', 'description',
       'time_point', 'file', 'found_taxa', 'total_taxa', 'found_fraction',
       'found_abundance_fraction', 'medium', 'direction', 'metabolite', 'flux',
       'reaction', 'name', 'molecular_weight', 'C_number', 'N_number', 'hmdb',
       'inchi', 'kegg.compound', 'pubchem.compound', 'reaction.1'],
      dtype='object')

In [20]:
only_imports = merged_with_annotations
only_imports

,compartments,abundance,growth_rate,reactions,metabolites,taxon,tradeoff,sample_id,Unnamed: 0,description,...,reaction,name,molecular_weight,C_number,N_number,hmdb,inchi,kegg.compound,pubchem.compound,reaction.1
0,Akkermansia,0.133546,7.736626e-02,2274,1386,Akkermansia,0.7,SRR15032081,3,High fermented food diet,...,EX_MGlcn144(e),mucin-type O-glycan No 144,NaN,28,2,NaN,NaN,NaN,NaN,EX_MGlcn144(e)
1,Eubacterium,0.051118,1.011622e-01,2073,1577,Eubacterium,0.7,SRR15032081,3,High fermented food diet,...,EX_MGlcn144(e),mucin-type O-glycan No 144,NaN,28,2,NaN,NaN,NaN,NaN,EX_MGlcn144(e)
2,Faecalibacterium,0.038339,7.753369e-02,1986,1472,Faecalibacterium,0.7,SRR15032081,3,High fermented food diet,...,EX_MGlcn144(e),mucin-type O-glycan No 144,NaN,28,2,NaN,NaN,NaN,NaN,EX_MGlcn144(e)
3,Bifidobacterium,0.060697,1.373560e-01,3108,1734,Bifidobacterium,0.7,SRR15032099,21,High fermented food diet,...,EX_MGlcn144(e),mucin-type O-glycan No 144,NaN,28,2,NaN,NaN,NaN,NaN,EX_MGlcn144(e)
4,Bacteroides,0.267677,5.714096e-01,3293,1883,Bacteroides,0.7,SRR15032282,78,High fermented food diet,...,EX_MGlcn144(e),mucin-type O-glycan No 144,NaN,28,2,NaN,NaN,NaN,NaN,EX_MGlcn144(e)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104841,Alistipes,0.066253,9.328558e-02,2650,1613,Alistipes,0.7,SRR15032499,295,High fermented food diet,...,EX_tchola(e),taurocholate,515.703,26,1,HMDB00036,NaN,NaN,440567.0,EX_tchola(e)
104842,Bacteroides,0.562325,2.644783e-01,3293,1883,Bacteroides,0.7,SRR15032499,295,High fermented food diet,...,EX_tchola(e),taurocholate,515.703,26,1,HMDB00036,NaN,NaN,440567.0,EX_tchola(e)
104843,Blautia,0.051763,8.718740e-07,2808,1732,Blautia,0.7,SRR15032499,295,High fermented food diet,...,EX_tchola(e),taurocholate,515.703,26,1,HMDB00036,NaN,NaN,440567.0,EX_tchola(e)
104844,Faecalibacterium,0.081267,1.323349e-02,1986,1472,Faecalibacterium,0.7,SRR15032499,295,High fermented food diet,...,EX_tchola(e),taurocholate,515.703,26,1,HMDB00036,NaN,NaN,440567.0,EX_tchola(e)
104845,Roseburia,0.076292,1.347324e-02,2357,1567,Roseburia,0.7,SRR15032499,295,High fermented food diet,...,EX_tchola(e),taurocholate,515.703,26,1,HMDB00036,NaN,NaN,440567.0,EX_tchola(e)

In [21]:
taxon_imports_table = only_imports[["taxon", "direction", "sample_id", "medium", "name", "flux"]]

In [22]:
taxon_imports_table

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104841,Alistipes,import,SRR15032499,fermented,taurocholate,-0.000139
104842,Bacteroides,import,SRR15032499,fermented,taurocholate,-0.000017
104843,Blautia,import,SRR15032499,fermented,taurocholate,-0.000177
104844,Faecalibacterium,import,SRR15032499,fermented,taurocholate,-0.000113
104845,Roseburia,import,SRR15032499,fermented,taurocholate,-0.000120

next step 
- comparing the metabolite imports of the most abundant taxa before and after diet intervention

# bacteroides

In [23]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [24]:
western_bacteroides_only = western_only.loc[western_only['taxon'] == 'Bacteroides']
western_bacteroides_only

,taxon,direction,sample_id,medium,name,flux
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
63,Bacteroides,import,SRR15032081,western,hydrogenphosphate,-18.557204
121,Bacteroides,import,SRR15032099,western,hydrogenphosphate,-37.953074
151,Bacteroides,import,SRR15032112,western,hydrogenphosphate,-18.938989
163,Bacteroides,import,SRR15032115,western,hydrogenphosphate,-17.728793
...,...,...,...,...,...,...
104813,Bacteroides,import,SRR15032439,western,released mucin-type O-glycan No 135,-0.000007
104823,Bacteroides,import,SRR15032392,western,Nitrogen,-0.000001
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049

In [25]:
mean_import_of_western_bacteroides = western_bacteroides_only["flux"].mean()
mean_import_of_western_bacteroides

-13.464623429376656

In [26]:
mean_import_of_western_bacteroides = western_bacteroides_only.groupby('name')["flux"].mean()
mean_import_of_western_bacteroides

name
(R)-lactate                                         -50.622811
(S)-lactaldehyde                                    -35.421978
(S)-lactate                                         -46.299493
(S)-propane-1,2-diol                                -29.994424
2-Demethylmenaquinone 8                              -0.000001
                                                       ...
starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})    -0.000002
sulfate                                              -0.141754
tetradecanoate (n-C14:0)                            -14.568705
thiosulfate(2-)                                      -0.024979
uracil                                              -58.118870
Name: flux, Length: 396, dtype: float64

In [27]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [28]:
high_fiber_bacteroides_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Bacteroides']
high_fiber_bacteroides_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
87,Bacteroides,import,SRR15032089,high_fiber,hydrogenphosphate,-14.936859
103,Bacteroides,import,SRR15032083,high_fiber,hydrogenphosphate,-44.994203
105,Bacteroides,import,SRR15032082,high_fiber,hydrogenphosphate,-60.547483
...,...,...,...,...,...,...
104353,Bacteroides,import,SRR15032475,high_fiber,3-Dehydrochenodeoxycholate,-0.073540
104354,Bacteroides,import,SRR15032482,high_fiber,3-Dehydrochenodeoxycholate,-0.027590
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800

In [29]:
mean_import_of_high_fiber_bacteroides = high_fiber_bacteroides_only["flux"].mean()
mean_import_of_high_fiber_bacteroides

-18.370876588894085

In [30]:
mean_import_of_high_fiber_bacteroides = high_fiber_bacteroides_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_bacteroides

name
(R)-lactate                -49.809350
(S)-lactaldehyde           -35.490875
(S)-lactate                -42.909849
(S)-malate(2-)             -15.413889
(S)-propane-1,2-diol       -40.039460
                              ...
proton                     -90.675300
sulfate                     -0.387960
tetradecanoate (n-C14:0)   -15.639674
thiosulfate(2-)             -0.030674
uracil                     -57.194970
Name: flux, Length: 108, dtype: float64

In [31]:
mean_import_of_western_bacteroides

name
(R)-lactate                                         -50.622811
(S)-lactaldehyde                                    -35.421978
(S)-lactate                                         -46.299493
(S)-propane-1,2-diol                                -29.994424
2-Demethylmenaquinone 8                              -0.000001
                                                       ...
starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})    -0.000002
sulfate                                              -0.141754
tetradecanoate (n-C14:0)                            -14.568705
thiosulfate(2-)                                      -0.024979
uracil                                              -58.118870
Name: flux, Length: 396, dtype: float64

In [32]:
mean_import_of_high_fiber_bacteroides

name
(R)-lactate                -49.809350
(S)-lactaldehyde           -35.490875
(S)-lactate                -42.909849
(S)-malate(2-)             -15.413889
(S)-propane-1,2-diol       -40.039460
                              ...
proton                     -90.675300
sulfate                     -0.387960
tetradecanoate (n-C14:0)   -15.639674
thiosulfate(2-)             -0.030674
uracil                     -57.194970
Name: flux, Length: 108, dtype: float64

In [33]:
western_bacteroides_imports = pd.DataFrame (mean_import_of_western_bacteroides, columns = ['flux'])

In [34]:
western_bacteroides_imports.rename(columns={"flux": "western_flux"}, inplace=True)

In [35]:
western_bacteroides_imports

                                                   western_flux
name
(R)-lactate                                          -50.622811
(S)-lactaldehyde                                     -35.421978
(S)-lactate                                          -46.299493
(S)-propane-1,2-diol                                 -29.994424
2-Demethylmenaquinone 8                               -0.000001
...                                                         ...
starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})     -0.000002
sulfate                                               -0.141754
tetradecanoate (n-C14:0)                             -14.568705
thiosulfate(2-)                                       -0.024979
uracil                                               -58.118870

[396 rows x 1 columns]

In [36]:
high_fiber_bacteroides_imports = pd.DataFrame (mean_import_of_high_fiber_bacteroides, columns = ['flux'])

In [37]:
high_fiber_bacteroides_imports.rename(columns={"flux": "high_fiber_flux"}, inplace=True)

In [38]:
high_fiber_bacteroides_imports

                          high_fiber_flux
name
(R)-lactate                    -49.809350
(S)-lactaldehyde               -35.490875
(S)-lactate                    -42.909849
(S)-malate(2-)                 -15.413889
(S)-propane-1,2-diol           -40.039460
...                                   ...
proton                         -90.675300
sulfate                         -0.387960
tetradecanoate (n-C14:0)       -15.639674
thiosulfate(2-)                 -0.030674
uracil                         -57.194970

[108 rows x 1 columns]

In [39]:
combined_diet_fluxes = pd.concat([western_bacteroides_imports['western_flux'], high_fiber_bacteroides_imports['high_fiber_flux']], axis=1, keys= ['western_bacteroides_imports', 'high_fiber_bacteroides_imports'])

In [40]:
combined_diet_fluxes

,western_bacteroides_imports,high_fiber_bacteroides_imports
name,,
(R)-lactate,-50.622811,-49.809350
(S)-lactaldehyde,-35.421978,-35.490875
(S)-lactate,-46.299493,-42.909849
"(S)-propane-1,2-diol",-29.994424,-40.039460
2-Demethylmenaquinone 8,-0.000001,NaN
...,...,...
Isochenodeoxycholate,NaN,-0.046474
Isocholate,NaN,-0.046431
chondroitin sulfate B / dermatan sulfate (IdoA2S-GalNAc4S) proteoglycan,NaN,-0.000221
ethanol,NaN,-8.498090
heparan sulfate proteoglycan,NaN,-0.002250

In [41]:
bacteroides_imports_for_both_diets = combined_diet_fluxes.dropna()

In [42]:
bacteroides_imports_for_both_diets

,western_bacteroides_imports,high_fiber_bacteroides_imports
name,,
(R)-lactate,-50.622811,-49.809350
(S)-lactaldehyde,-35.421978,-35.490875
(S)-lactate,-46.299493,-42.909849
"(S)-propane-1,2-diol",-29.994424,-40.039460
2-Oxobutanoate,-42.282852,-45.545415
...,...,...
proton,-87.202176,-90.675300
sulfate,-0.141754,-0.387960
tetradecanoate (n-C14:0),-14.568705,-15.639674
thiosulfate(2-),-0.024979,-0.030674
uracil,-58.118870,-57.194970

finding the euclidean distance:

In [43]:
bacteroides_euclidean_distance = ((bacteroides_imports_for_both_diets.western_bacteroides_imports - bacteroides_imports_for_both_diets.high_fiber_bacteroides_imports)**2).sum()**(1/2)

bacteroides_euclidean_distance

63.35243012853294

# prevotella

In [44]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [45]:
western_prevotella_only = western_only.loc[western_only['taxon'] == 'Prevotella']
western_prevotella_only

,taxon,direction,sample_id,medium,name,flux
12,Prevotella,import,SRR15032323,western,mucin-type O-glycan No 144,-0.000002
276,Prevotella,import,SRR15032195,western,hydrogenphosphate,-47.939886
359,Prevotella,import,SRR15032287,western,hydrogenphosphate,-36.087967
608,Prevotella,import,SRR15032334,western,hydrogenphosphate,-66.619241
698,Prevotella,import,SRR15032384,western,hydrogenphosphate,-81.096947
...,...,...,...,...,...,...
104752,Prevotella,import,SRR15032324,western,released mucin-type O-glycan No 173,-0.000003
104763,Prevotella,import,SRR15032324,western,released mucin-type O-glycan No 140,-0.000001
104779,Prevotella,import,SRR15032323,western,released mucin-type O-glycan No 145,-0.000003
104782,Prevotella,import,SRR15032324,western,released mucin-type O-glycan No 145,-0.000002
104820,Prevotella,import,SRR15032351,western,Nitrogen,-0.000001

In [46]:
mean_import_of_western_prevotella = western_prevotella_only.groupby('name')["flux"].mean()
mean_import_of_western_prevotella

name
(R)-Pantothenate            -0.002098
(R)-lactate                 -5.248603
(S)-lactate                -10.586181
(S)-malate(2-)             -39.995879
2-Oxobutanoate             -95.079619
                              ...
sialyl-Tn antigen           -0.000002
sulfate                     -0.132139
tetradecanoate (n-C14:0)    -0.729384
thiosulfate(2-)             -0.155418
uracil                     -83.207332
Name: flux, Length: 214, dtype: float64

In [47]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [48]:
high_fiber_prevotella_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Prevotella']
high_fiber_prevotella_only

,taxon,direction,sample_id,medium,name,flux
79,Prevotella,import,SRR15032095,high_fiber,hydrogenphosphate,-64.707708
99,Prevotella,import,SRR15032079,high_fiber,hydrogenphosphate,-46.533284
118,Prevotella,import,SRR15032103,high_fiber,hydrogenphosphate,-33.397910
206,Prevotella,import,SRR15032136,high_fiber,hydrogenphosphate,-58.256250
272,Prevotella,import,SRR15032184,high_fiber,hydrogenphosphate,-51.883256
...,...,...,...,...,...,...
102223,Prevotella,import,SRR15032352,high_fiber,thiosulfate(2-),-0.219051
102389,Prevotella,import,SRR15032095,high_fiber,octadecanoate (n-C18:0),-0.037240
102435,Prevotella,import,SRR15032136,high_fiber,octadecanoate (n-C18:0),-0.031265
102572,Prevotella,import,SRR15032339,high_fiber,octadecanoate (n-C18:0),-0.034172
102641,Prevotella,import,SRR15032403,high_fiber,octadecanoate (n-C18:0),-0.012738

In [49]:
mean_import_of_high_fiber_prevotella = high_fiber_prevotella_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_prevotella

name
(R)-lactate                 -9.813017
(S)-lactate                -10.087787
(S)-malate(2-)             -25.544395
2-Oxobutanoate             -89.468921
2-Oxoglutarate              -4.665738
                              ...
proton                     -91.799223
sulfate                     -0.240655
tetradecanoate (n-C14:0)    -0.065293
thiosulfate(2-)             -0.077733
uracil                     -81.512629
Name: flux, Length: 82, dtype: float64

In [50]:
western_prevotella_imports = pd.DataFrame (mean_import_of_western_prevotella, columns = ['flux'])

In [51]:
western_prevotella_imports.rename(columns={"flux": "western_flux_prevotella"}, inplace=True)

In [52]:
western_prevotella_imports

                          western_flux_prevotella
name
(R)-Pantothenate                        -0.002098
(R)-lactate                             -5.248603
(S)-lactate                            -10.586181
(S)-malate(2-)                         -39.995879
2-Oxobutanoate                         -95.079619
...                                           ...
sialyl-Tn antigen                       -0.000002
sulfate                                 -0.132139
tetradecanoate (n-C14:0)                -0.729384
thiosulfate(2-)                         -0.155418
uracil                                 -83.207332

[214 rows x 1 columns]

In [53]:
high_fiber_prevotella_imports = pd.DataFrame (mean_import_of_high_fiber_prevotella, columns = ['flux'])

In [54]:
high_fiber_prevotella_imports.rename(columns={"flux": "high_fiber_flux_prevotella"}, inplace=True)

In [55]:
high_fiber_prevotella_imports

                          high_fiber_flux_prevotella
name
(R)-lactate                                -9.813017
(S)-lactate                               -10.087787
(S)-malate(2-)                            -25.544395
2-Oxobutanoate                            -89.468921
2-Oxoglutarate                             -4.665738
...                                              ...
proton                                    -91.799223
sulfate                                    -0.240655
tetradecanoate (n-C14:0)                   -0.065293
thiosulfate(2-)                            -0.077733
uracil                                    -81.512629

[82 rows x 1 columns]

In [56]:
combined_diet_fluxes_prevotella = pd.concat([western_prevotella_imports['western_flux_prevotella'], high_fiber_prevotella_imports['high_fiber_flux_prevotella']], axis=1, keys= ['western_prevotella_imports', 'high_fiber_prevotella_imports'])

In [57]:
combined_diet_fluxes_prevotella

,western_prevotella_imports,high_fiber_prevotella_imports
name,,
(R)-Pantothenate,-0.002098,NaN
(R)-lactate,-5.248603,-9.813017
(S)-lactate,-10.586181,-10.087787
(S)-malate(2-),-39.995879,-25.544395
2-Oxobutanoate,-95.079619,-89.468921
...,...,...
sulfate,-0.132139,-0.240655
tetradecanoate (n-C14:0),-0.729384,-0.065293
thiosulfate(2-),-0.155418,-0.077733
uracil,-83.207332,-81.512629
L-asparagine,NaN,-2.658086

In [58]:
prevotella_imports_for_both_diets = combined_diet_fluxes_prevotella.dropna()

In [59]:
prevotella_imports_for_both_diets

,western_prevotella_imports,high_fiber_prevotella_imports
name,,
(R)-lactate,-5.248603,-9.813017
(S)-lactate,-10.586181,-10.087787
(S)-malate(2-),-39.995879,-25.544395
2-Oxobutanoate,-95.079619,-89.468921
2-Oxoglutarate,-9.265928,-4.665738
...,...,...
proton,-89.080654,-91.799223
sulfate,-0.132139,-0.240655
tetradecanoate (n-C14:0),-0.729384,-0.065293
thiosulfate(2-),-0.155418,-0.077733
uracil,-83.207332,-81.512629

finding euclidean distance

In [60]:
prevotella_euclidean_distance = ((prevotella_imports_for_both_diets.western_prevotella_imports - prevotella_imports_for_both_diets.high_fiber_prevotella_imports)**2).sum()**(1/2)

prevotella_euclidean_distance

64.56405495878849

# faecalibacterium

In [61]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [62]:
western_faecalibacterium_only = western_only.loc[western_only['taxon'] == 'Faecalibacterium']
western_faecalibacterium_only

,taxon,direction,sample_id,medium,name,flux
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
11,Faecalibacterium,import,SRR15032323,western,mucin-type O-glycan No 144,-0.000001
22,Faecalibacterium,import,SRR15032081,western,released mucin-type O-glycan No 68,-0.000006
25,Faecalibacterium,import,SRR15032099,western,released mucin-type O-glycan No 68,-0.000002
30,Faecalibacterium,import,SRR15032293,western,released mucin-type O-glycan No 68,-0.000011
...,...,...,...,...,...,...
104757,Faecalibacterium,import,SRR15032363,western,released mucin-type O-glycan No 173,-0.000001
104762,Faecalibacterium,import,SRR15032293,western,released mucin-type O-glycan No 140,-0.000002
104792,Faecalibacterium,import,SRR15032392,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000006
104795,Faecalibacterium,import,SRR15032439,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000002
104800,Faecalibacterium,import,SRR15032392,western,Biotin,-0.000001

In [63]:
mean_import_of_western_faecalibacterium = western_faecalibacterium_only.groupby('name')["flux"].mean()
mean_import_of_western_faecalibacterium

name
(R)-Pantothenate                                     -0.003295
(R)-lactate                                          -6.205649
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)     -0.000002
12-Dehydrocholate                                    -8.623386
3-methyl-2-oxopentanoate                             -7.946322
                                                        ...
released mucin-type O-glycan No 97                   -0.000002
released mucin-type O-glycan No 98                   -0.000002
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})   -0.000004
sulfate                                              -0.195368
tetradecanoate (n-C14:0)                             -1.986389
Name: flux, Length: 269, dtype: float64

In [64]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [65]:
high_fiber_faecalibacterium_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Faecalibacterium']
high_fiber_faecalibacterium_only

,taxon,direction,sample_id,medium,name,flux
78,Faecalibacterium,import,SRR15032095,high_fiber,hydrogenphosphate,-0.056395
89,Faecalibacterium,import,SRR15032089,high_fiber,hydrogenphosphate,-0.030137
97,Faecalibacterium,import,SRR15032079,high_fiber,hydrogenphosphate,-0.034618
107,Faecalibacterium,import,SRR15032082,high_fiber,hydrogenphosphate,-0.112814
116,Faecalibacterium,import,SRR15032103,high_fiber,hydrogenphosphate,-0.047895
...,...,...,...,...,...,...
102424,Faecalibacterium,import,SRR15032121,high_fiber,octadecanoate (n-C18:0),-0.004820
102479,Faecalibacterium,import,SRR15032288,high_fiber,octadecanoate (n-C18:0),-0.001636
103081,Faecalibacterium,import,SRR15032119,high_fiber,Dimer GalNAc-GlcA,-0.000003
103088,Faecalibacterium,import,SRR15032428,high_fiber,Dimer GalNAc-GlcA,-0.000001
104129,Faecalibacterium,import,SRR15032119,high_fiber,Dimer GalNAc-IdoA2S,-0.000004

In [66]:
mean_import_of_high_fiber_faecalibacterium = high_fiber_faecalibacterium_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_faecalibacterium

name
(R)-lactate                -28.348469
12-Dehydrocholate          -10.630604
3-methyl-2-oxopentanoate    -3.415913
Ammonium                   -12.138403
Chloride                    -0.000566
                              ...
potassium                   -0.000545
proton                     -34.049277
sulfate                     -0.093502
tetradecanoate (n-C14:0)    -2.057449
uracil                     -22.182488
Name: flux, Length: 80, dtype: float64

In [67]:
western_faecalibacterium_imports = pd.DataFrame (mean_import_of_western_faecalibacterium, columns = ['flux'])

In [68]:
western_faecalibacterium_imports.rename(columns={"flux": "western_flux_faecalibacterium"}, inplace=True)

In [69]:
western_faecalibacterium_imports

                                                    western_flux_faecalibacterium
name
(R)-Pantothenate                                                        -0.003295
(R)-lactate                                                             -6.205649
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)                        -0.000002
12-Dehydrocholate                                                       -8.623386
3-methyl-2-oxopentanoate                                                -7.946322
...                                                                           ...
released mucin-type O-glycan No 97                                      -0.000002
released mucin-type O-glycan No 98                                      -0.000002
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})                      -0.000004
sulfate                                                                 -0.195368
tetradecanoate (n-C14:0)                                                -1.986389

[269 rows x 1 columns]

In [70]:
high_fiber_faecalibacterium_imports = pd.DataFrame (mean_import_of_high_fiber_faecalibacterium, columns = ['flux'])

In [71]:
high_fiber_faecalibacterium_imports.rename(columns={"flux": "high_fiber_flux_faecalibacterium"}, inplace=True)

In [72]:
high_fiber_faecalibacterium_imports

                          high_fiber_flux_faecalibacterium
name
(R)-lactate                                     -28.348469
12-Dehydrocholate                               -10.630604
3-methyl-2-oxopentanoate                         -3.415913
Ammonium                                        -12.138403
Chloride                                         -0.000566
...                                                    ...
potassium                                        -0.000545
proton                                          -34.049277
sulfate                                          -0.093502
tetradecanoate (n-C14:0)                         -2.057449
uracil                                          -22.182488

[80 rows x 1 columns]

In [73]:
combined_diet_fluxes_faecalibacterium = pd.concat([western_faecalibacterium_imports['western_flux_faecalibacterium'], high_fiber_faecalibacterium_imports['high_fiber_flux_faecalibacterium']], axis=1, keys= ['western_faecalibacterium_imports', 'high_fiber_faecalibacterium_imports'])

In [74]:
combined_diet_fluxes_faecalibacterium

,western_faecalibacterium_imports,high_fiber_faecalibacterium_imports
name,,
(R)-Pantothenate,-0.003295,NaN
(R)-lactate,-6.205649,-28.348469
"1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)",-0.000002,NaN
12-Dehydrocholate,-8.623386,-10.630604
3-methyl-2-oxopentanoate,-7.946322,-3.415913
...,...,...
"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})",-0.000004,NaN
sulfate,-0.195368,-0.093502
tetradecanoate (n-C14:0),-1.986389,-2.057449
chondroitin sulfate B / dermatan sulfate (IdoA2S-GalNAc4S) proteoglycan,NaN,-0.000592
uracil,NaN,-22.182488

In [75]:
faecalibacterium_imports_for_both_diets = combined_diet_fluxes_faecalibacterium.dropna()

In [76]:
faecalibacterium_imports_for_both_diets

,western_faecalibacterium_imports,high_fiber_faecalibacterium_imports
name,,
(R)-lactate,-6.205649,-28.348469
12-Dehydrocholate,-8.623386,-10.630604
3-methyl-2-oxopentanoate,-7.946322,-3.415913
Ammonium,-22.634971,-12.138403
Chloride,-0.002003,-0.000566
...,...,...
octadecanoate (n-C18:0),-0.005237,-0.003228
potassium,-0.001969,-0.000545
proton,-43.267503,-34.049277
sulfate,-0.195368,-0.093502
tetradecanoate (n-C14:0),-1.986389,-2.057449

In [77]:
faecalibacterium_euclidean_distance = ((faecalibacterium_imports_for_both_diets.western_faecalibacterium_imports - faecalibacterium_imports_for_both_diets.high_fiber_faecalibacterium_imports)**2).sum()**(1/2)

faecalibacterium_euclidean_distance

48.68283693595469

# Roseburia

In [78]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [79]:
western_roseburia_only = western_only.loc[western_only['taxon'] == 'Roseburia']
western_roseburia_only

,taxon,direction,sample_id,medium,name,flux
6,Roseburia,import,SRR15032293,western,mucin-type O-glycan No 144,-0.000003
13,Roseburia,import,SRR15032323,western,mucin-type O-glycan No 144,-0.000011
14,Roseburia,import,SRR15032344,western,mucin-type O-glycan No 144,-0.000001
23,Roseburia,import,SRR15032081,western,released mucin-type O-glycan No 68,-0.000004
26,Roseburia,import,SRR15032099,western,released mucin-type O-glycan No 68,-0.000004
...,...,...,...,...,...,...
104772,Roseburia,import,SRR15032323,western,released mucin-type O-glycan No 149,-0.000008
104780,Roseburia,import,SRR15032323,western,released mucin-type O-glycan No 145,-0.000009
104786,Roseburia,import,SRR15032439,western,released mucin-type O-glycan No 145,-0.000002
104793,Roseburia,import,SRR15032392,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000008
104797,Roseburia,import,SRR15032439,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000002

In [80]:
mean_import_of_western_roseburia = western_roseburia_only.groupby('name')["flux"].mean()
mean_import_of_western_roseburia

name
(R)-Pantothenate                                      -0.002982
(R)-lactate                                          -51.907105
(S)-propane-1,2-diol                                  -0.006050
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)      -0.000002
Adenosylcobalamin                                     -0.000007
                                                        ...
released mucin-type O-glycan No 99                    -0.000004
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})    -0.000005
sulfate                                               -0.001865
tetradecanoate (n-C14:0)                              -1.982845
uracil                                                -2.370423
Name: flux, Length: 389, dtype: float64

In [81]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [82]:
high_fiber_roseburia_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Roseburia']
high_fiber_roseburia_only

,taxon,direction,sample_id,medium,name,flux
80,Roseburia,import,SRR15032095,high_fiber,hydrogenphosphate,-0.047411
109,Roseburia,import,SRR15032082,high_fiber,hydrogenphosphate,-0.064923
131,Roseburia,import,SRR15032104,high_fiber,hydrogenphosphate,-0.078176
161,Roseburia,import,SRR15032119,high_fiber,hydrogenphosphate,-0.060464
207,Roseburia,import,SRR15032136,high_fiber,hydrogenphosphate,-0.038690
...,...,...,...,...,...,...
99435,Roseburia,import,SRR15032461,high_fiber,O2,-1.337319
99448,Roseburia,import,SRR15032472,high_fiber,O2,-0.000047
101762,Roseburia,import,SRR15032119,high_fiber,L-lysinium(1+),-0.001871
101962,Roseburia,import,SRR15032494,high_fiber,L-lysinium(1+),-0.009683
102684,Roseburia,import,SRR15032458,high_fiber,octadecanoate (n-C18:0),-0.001911

In [83]:
mean_import_of_high_fiber_roseburia = high_fiber_roseburia_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_roseburia

name
(R)-lactate                -32.508383
Ammonium                   -18.506904
Chloride                    -0.000537
Citrate                     -0.000550
Co2+                        -0.000494
                              ...
octadecanoate (n-C18:0)     -0.001911
potassium                   -0.000537
sulfate                     -0.000537
tetradecanoate (n-C14:0)    -2.242054
uracil                      -3.808581
Name: flux, Length: 67, dtype: float64

In [84]:
western_roseburia_imports = pd.DataFrame (mean_import_of_western_roseburia, columns = ['flux'])

In [85]:
western_roseburia_imports.rename(columns={"flux": "western_flux_roseburia"}, inplace=True)

In [86]:
western_roseburia_imports

                                                    western_flux_roseburia
name
(R)-Pantothenate                                                 -0.002982
(R)-lactate                                                     -51.907105
(S)-propane-1,2-diol                                             -0.006050
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)                 -0.000002
Adenosylcobalamin                                                -0.000007
...                                                                    ...
released mucin-type O-glycan No 99                               -0.000004
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})               -0.000005
sulfate                                                          -0.001865
tetradecanoate (n-C14:0)                                         -1.982845
uracil                                                           -2.370423

[389 rows x 1 columns]

In [87]:
high_fiber_roseburia_imports = pd.DataFrame (mean_import_of_high_fiber_roseburia, columns = ['flux'])

In [88]:
high_fiber_roseburia_imports.rename(columns={"flux": "high_fiber_flux_roseburia"}, inplace=True)

In [89]:
high_fiber_roseburia_imports

                          high_fiber_flux_roseburia
name
(R)-lactate                              -32.508383
Ammonium                                 -18.506904
Chloride                                  -0.000537
Citrate                                   -0.000550
Co2+                                      -0.000494
...                                             ...
octadecanoate (n-C18:0)                   -0.001911
potassium                                 -0.000537
sulfate                                   -0.000537
tetradecanoate (n-C14:0)                  -2.242054
uracil                                    -3.808581

[67 rows x 1 columns]

In [90]:
combined_diet_fluxes_roseburia = pd.concat([western_roseburia_imports['western_flux_roseburia'], high_fiber_roseburia_imports['high_fiber_flux_roseburia']], axis=1, keys= ['western_roseburia_imports', 'high_fiber_roseburia_imports'])

In [91]:
combined_diet_fluxes_roseburia

,western_roseburia_imports,high_fiber_roseburia_imports
name,,
(R)-Pantothenate,-0.002982,NaN
(R)-lactate,-51.907105,-32.508383
"(S)-propane-1,2-diol",-0.006050,NaN
"1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)",-0.000002,NaN
Adenosylcobalamin,-0.000007,NaN
...,...,...
"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})",-0.000005,NaN
sulfate,-0.001865,-0.000537
tetradecanoate (n-C14:0),-1.982845,-2.242054
uracil,-2.370423,-3.808581
Glycine,NaN,-6.616224

In [92]:
roseburia_imports_for_both_diets = combined_diet_fluxes_roseburia.dropna()

In [93]:
roseburia_imports_for_both_diets

,western_roseburia_imports,high_fiber_roseburia_imports
name,,
(R)-lactate,-51.907105,-32.508383
Ammonium,-20.961509,-18.506904
Chloride,-0.001865,-0.000537
Citrate,-0.001837,-0.000550
Co2+,-0.001834,-0.000494
...,...,...
octadecanoate (n-C18:0),-0.001325,-0.001911
potassium,-0.001865,-0.000537
sulfate,-0.001865,-0.000537
tetradecanoate (n-C14:0),-1.982845,-2.242054
uracil,-2.370423,-3.808581

In [94]:
roseburia_euclidean_distance = ((roseburia_imports_for_both_diets.western_roseburia_imports - roseburia_imports_for_both_diets.high_fiber_roseburia_imports)**2).sum()**(1/2)

roseburia_euclidean_distance

27.39142994145541

# Blautia

In [95]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [96]:
western_blautia_only = western_only.loc[western_only['taxon'] == 'Blautia']
western_blautia_only

,taxon,direction,sample_id,medium,name,flux
15,Blautia,import,SRR15032439,western,mucin-type O-glycan No 144,-0.000002
20,Blautia,import,SRR15032081,western,released mucin-type O-glycan No 68,-0.000001
28,Blautia,import,SRR15032293,western,released mucin-type O-glycan No 68,-0.000018
43,Blautia,import,SRR15032344,western,released mucin-type O-glycan No 68,-0.000002
49,Blautia,import,SRR15032384,western,released mucin-type O-glycan No 68,-0.000004
...,...,...,...,...,...,...
104814,Blautia,import,SRR15032439,western,released mucin-type O-glycan No 135,-0.000001
104815,Blautia,import,SRR15032323,western,Nitrogen,-0.000001
104818,Blautia,import,SRR15032324,western,Nitrogen,-0.000001
104819,Blautia,import,SRR15032334,western,Nitrogen,-0.000003
104821,Blautia,import,SRR15032384,western,Nitrogen,-0.000001

In [97]:
mean_import_of_western_blautia = western_blautia_only.groupby('name')["flux"].mean()
mean_import_of_western_blautia

name
(R)-Pantothenate                                    -0.003154
(R)-lactate                                        -53.846407
(S)-lactate                                        -52.996872
(S)-propane-1,2-diol                               -80.655862
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)    -0.000002
                                                      ...
sialyl-T antigen                                    -0.000005
sialyl-Tn antigen                                   -0.000005
sulfate                                             -1.333703
thiosulfate(2-)                                     -0.101832
uracil                                              -0.119477
Name: flux, Length: 449, dtype: float64

In [98]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [99]:
high_fiber_blautia_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Blautia']
high_fiber_blautia_only

,taxon,direction,sample_id,medium,name,flux
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
88,Blautia,import,SRR15032089,high_fiber,hydrogenphosphate,-5.551465
96,Blautia,import,SRR15032079,high_fiber,hydrogenphosphate,-9.220314
104,Blautia,import,SRR15032083,high_fiber,hydrogenphosphate,-7.777798
...,...,...,...,...,...,...
102382,Blautia,import,SRR15032500,high_fiber,2-Dehydro-3-deoxy-D-gluconate,-0.001381
102383,Blautia,import,SRR15032505,high_fiber,2-Dehydro-3-deoxy-D-gluconate,-0.001331
102384,Blautia,import,SRR15032503,high_fiber,2-Dehydro-3-deoxy-D-gluconate,-0.001490
102408,Blautia,import,SRR15032104,high_fiber,octadecanoate (n-C18:0),-0.000294
102615,Blautia,import,SRR15032373,high_fiber,octadecanoate (n-C18:0),-0.000151

In [100]:
mean_import_of_high_fiber_blautia = high_fiber_blautia_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_blautia

name
(R)-lactate                     -54.519062
(S)-lactate                     -52.357205
(S)-propane-1,2-diol            -84.472959
2-Dehydro-3-deoxy-D-gluconate    -0.001249
Ammonium                        -45.831205
                                   ...
octadecanoate (n-C18:0)          -0.000223
potassium                        -0.000505
proton                          -65.154104
sulfate                          -0.870799
thiosulfate(2-)                  -0.098400
Name: flux, Length: 76, dtype: float64

In [101]:
western_blautia_imports = pd.DataFrame (mean_import_of_western_blautia, columns = ['flux'])

In [102]:
western_blautia_imports.rename(columns={"flux": "western_flux_blautia"}, inplace=True)

In [103]:
western_blautia_imports

                                                  western_flux_blautia
name
(R)-Pantothenate                                             -0.003154
(R)-lactate                                                 -53.846407
(S)-lactate                                                 -52.996872
(S)-propane-1,2-diol                                        -80.655862
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)             -0.000002
...                                                                ...
sialyl-T antigen                                             -0.000005
sialyl-Tn antigen                                            -0.000005
sulfate                                                      -1.333703
thiosulfate(2-)                                              -0.101832
uracil                                                       -0.119477

[449 rows x 1 columns]

In [104]:
high_fiber_blautia_imports = pd.DataFrame (mean_import_of_high_fiber_blautia, columns = ['flux'])

In [105]:
high_fiber_blautia_imports.rename(columns={"flux": "high_fiber_flux_blautia"}, inplace=True)

In [106]:
high_fiber_blautia_imports

                               high_fiber_flux_blautia
name
(R)-lactate                                 -54.519062
(S)-lactate                                 -52.357205
(S)-propane-1,2-diol                        -84.472959
2-Dehydro-3-deoxy-D-gluconate                -0.001249
Ammonium                                    -45.831205
...                                                ...
octadecanoate (n-C18:0)                      -0.000223
potassium                                    -0.000505
proton                                      -65.154104
sulfate                                      -0.870799
thiosulfate(2-)                              -0.098400

[76 rows x 1 columns]

In [107]:
combined_diet_fluxes_blautia = pd.concat([western_blautia_imports['western_flux_blautia'], high_fiber_blautia_imports['high_fiber_flux_blautia']], axis=1, keys= ['western_blautia_imports', 'high_fiber_blautia_imports'])

In [108]:
combined_diet_fluxes_blautia

,western_blautia_imports,high_fiber_blautia_imports
name,,
(R)-Pantothenate,-0.003154,NaN
(R)-lactate,-53.846407,-54.519062
(S)-lactate,-52.996872,-52.357205
"(S)-propane-1,2-diol",-80.655862,-84.472959
"1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)",-0.000002,NaN
...,...,...
sialyl-T antigen,-0.000005,NaN
sialyl-Tn antigen,-0.000005,NaN
sulfate,-1.333703,-0.870799
thiosulfate(2-),-0.101832,-0.098400
uracil,-0.119477,NaN

In [109]:
blautia_imports_for_both_diets = combined_diet_fluxes_blautia.dropna()

In [110]:
blautia_imports_for_both_diets

,western_blautia_imports,high_fiber_blautia_imports
name,,
(R)-lactate,-53.846407,-54.519062
(S)-lactate,-52.996872,-52.357205
"(S)-propane-1,2-diol",-80.655862,-84.472959
2-Dehydro-3-deoxy-D-gluconate,-0.514621,-0.001249
Ammonium,-39.819990,-45.831205
...,...,...
octadecanoate (n-C18:0),-0.007047,-0.000223
potassium,-0.002052,-0.000505
proton,-66.185996,-65.154104
sulfate,-1.333703,-0.870799
thiosulfate(2-),-0.101832,-0.098400

In [111]:
blautia_euclidean_distance = ((blautia_imports_for_both_diets.western_blautia_imports - blautia_imports_for_both_diets.high_fiber_blautia_imports)**2).sum()**(1/2)

blautia_euclidean_distance

28.36475275549472

# Alistipes

In [112]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [113]:
western_alistipes_only = western_only.loc[western_only['taxon'] == 'Alistipes']
western_alistipes_only

,taxon,direction,sample_id,medium,name,flux
8,Alistipes,import,SRR15032323,western,mucin-type O-glycan No 144,-0.000001
19,Alistipes,import,SRR15032081,western,released mucin-type O-glycan No 68,-0.000001
47,Alistipes,import,SRR15032384,western,released mucin-type O-glycan No 68,-0.000007
53,Alistipes,import,SRR15032392,western,released mucin-type O-glycan No 68,-0.000001
589,Alistipes,import,SRR15032344,western,hydrogenphosphate,-1.749855
...,...,...,...,...,...,...
104767,Alistipes,import,SRR15032323,western,released mucin-type O-glycan No 149,-0.000003
104773,Alistipes,import,SRR15032439,western,released mucin-type O-glycan No 149,-0.000003
104781,Alistipes,import,SRR15032324,western,released mucin-type O-glycan No 145,-0.000003
104787,Alistipes,import,SRR15032510,western,released mucin-type O-glycan No 145,-0.000003
104812,Alistipes,import,SRR15032344,western,released mucin-type O-glycan No 135,-0.000002

In [114]:
mean_import_of_western_alistipes = western_alistipes_only.groupby('name')["flux"].mean()
mean_import_of_western_alistipes

name
(R)-Pantothenate            -0.001493
(R)-lactate                -68.704137
2-Demethylmenaquinone 8     -0.000002
2-Oxoglutarate             -15.910667
2-deoxyadenosine           -18.267387
                              ...
sialyl-T antigen            -0.000005
sialyl-Tn antigen           -0.000005
sulfate                     -0.000873
tetradecanoate (n-C14:0)    -2.258106
uracil                     -55.178674
Name: flux, Length: 431, dtype: float64

In [115]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [116]:
high_fiber_alistipes_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Alistipes']
high_fiber_alistipes_only

,taxon,direction,sample_id,medium,name,flux
167,Alistipes,import,SRR15032121,high_fiber,hydrogenphosphate,-21.642279
1967,Alistipes,import,SRR15032095,high_fiber,Glycine,-45.311422
1975,Alistipes,import,SRR15032089,high_fiber,Glycine,-39.776000
1988,Alistipes,import,SRR15032083,high_fiber,Glycine,-58.982622
1992,Alistipes,import,SRR15032082,high_fiber,Glycine,-53.620560
...,...,...,...,...,...,...
102608,Alistipes,import,SRR15032372,high_fiber,octadecanoate (n-C18:0),-0.010824
102612,Alistipes,import,SRR15032373,high_fiber,octadecanoate (n-C18:0),-0.002547
102657,Alistipes,import,SRR15032423,high_fiber,octadecanoate (n-C18:0),-0.004230
102660,Alistipes,import,SRR15032428,high_fiber,octadecanoate (n-C18:0),-0.009166
102728,Alistipes,import,SRR15032494,high_fiber,octadecanoate (n-C18:0),-0.009082

In [117]:
mean_import_of_high_fiber_alistipes = high_fiber_alistipes_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_alistipes

name
(R)-lactate                -66.738824
2-Oxoglutarate             -11.511520
2-deoxyadenosine           -23.056857
4-hydroxybenzoate          -55.916727
Adenine                    -25.609691
                              ...
potassium                   -0.001044
proton                     -73.993715
sulfate                     -0.001044
tetradecanoate (n-C14:0)    -2.592348
uracil                     -55.865618
Name: flux, Length: 84, dtype: float64

In [118]:
western_alistipes_imports = pd.DataFrame (mean_import_of_western_alistipes, columns = ['flux'])

In [119]:
western_alistipes_imports.rename(columns={"flux": "western_flux_alistipes"}, inplace=True)

In [120]:
western_alistipes_imports

                          western_flux_alistipes
name
(R)-Pantothenate                       -0.001493
(R)-lactate                           -68.704137
2-Demethylmenaquinone 8                -0.000002
2-Oxoglutarate                        -15.910667
2-deoxyadenosine                      -18.267387
...                                          ...
sialyl-T antigen                       -0.000005
sialyl-Tn antigen                      -0.000005
sulfate                                -0.000873
tetradecanoate (n-C14:0)               -2.258106
uracil                                -55.178674

[431 rows x 1 columns]

In [121]:
high_fiber_alistipes_imports = pd.DataFrame (mean_import_of_high_fiber_alistipes, columns = ['flux'])

In [122]:
high_fiber_alistipes_imports.rename(columns={"flux": "high_fiber_flux_alistipes"}, inplace=True)

In [123]:
high_fiber_alistipes_imports

                          high_fiber_flux_alistipes
name
(R)-lactate                              -66.738824
2-Oxoglutarate                           -11.511520
2-deoxyadenosine                         -23.056857
4-hydroxybenzoate                        -55.916727
Adenine                                  -25.609691
...                                             ...
potassium                                 -0.001044
proton                                   -73.993715
sulfate                                   -0.001044
tetradecanoate (n-C14:0)                  -2.592348
uracil                                   -55.865618

[84 rows x 1 columns]

In [124]:
combined_diet_fluxes_alistipes = pd.concat([western_alistipes_imports['western_flux_alistipes'], high_fiber_alistipes_imports['high_fiber_flux_alistipes']], axis=1, keys= ['western_alistipes_imports', 'high_fiber_alistipes_imports'])

In [125]:
combined_diet_fluxes_alistipes

,western_alistipes_imports,high_fiber_alistipes_imports
name,,
(R)-Pantothenate,-0.001493,NaN
(R)-lactate,-68.704137,-66.738824
2-Demethylmenaquinone 8,-0.000002,NaN
2-Oxoglutarate,-15.910667,-11.511520
2-deoxyadenosine,-18.267387,-23.056857
...,...,...
sialyl-Tn antigen,-0.000005,NaN
sulfate,-0.000873,-0.001044
tetradecanoate (n-C14:0),-2.258106,-2.592348
uracil,-55.178674,-55.865618
Urea,NaN,-0.147937

In [126]:
alistipes_imports_for_both_diets = combined_diet_fluxes_alistipes.dropna()

In [127]:
alistipes_imports_for_both_diets

,western_alistipes_imports,high_fiber_alistipes_imports
name,,
(R)-lactate,-68.704137,-66.738824
2-Oxoglutarate,-15.910667,-11.511520
2-deoxyadenosine,-18.267387,-23.056857
4-hydroxybenzoate,-58.842055,-55.916727
Adenine,-24.370497,-25.609691
...,...,...
potassium,-0.000873,-0.001044
proton,-75.996451,-73.993715
sulfate,-0.000873,-0.001044
tetradecanoate (n-C14:0),-2.258106,-2.592348
uracil,-55.178674,-55.865618

In [128]:
alistipes_euclidean_distance = ((alistipes_imports_for_both_diets.western_alistipes_imports - alistipes_imports_for_both_diets.high_fiber_alistipes_imports)**2).sum()**(1/2)

alistipes_euclidean_distance

51.161930368231786

# Ruminococcus

In [129]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [130]:
western_ruminococcus_only = western_only.loc[western_only['taxon'] == 'Ruminococcus']
western_ruminococcus_only

,taxon,direction,sample_id,medium,name,flux
7,Ruminococcus,import,SRR15032293,western,mucin-type O-glycan No 144,-0.000001
17,Ruminococcus,import,SRR15032439,western,mucin-type O-glycan No 144,-0.000001
27,Ruminococcus,import,SRR15032099,western,released mucin-type O-glycan No 68,-0.000003
32,Ruminococcus,import,SRR15032293,western,released mucin-type O-glycan No 68,-0.000028
60,Ruminococcus,import,SRR15032439,western,released mucin-type O-glycan No 68,-0.000009
...,...,...,...,...,...,...
104794,Ruminococcus,import,SRR15032392,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000003
104798,Ruminococcus,import,SRR15032439,western,"starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Gl...",-0.000002
104799,Ruminococcus,import,SRR15032293,western,Biotin,-0.000001
104802,Ruminococcus,import,SRR15032439,western,Biotin,-0.000001
104825,Ruminococcus,import,SRR15032392,western,Nitrogen,-0.000001

In [131]:
mean_import_of_western_ruminococcus = western_ruminococcus_only.groupby('name')["flux"].mean()
mean_import_of_western_ruminococcus

name
(R)-lactate                                          -79.871701
(S)-lactate                                          -78.742605
(S)-propane-1,2-diol                                 -34.347199
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)      -0.000001
12-Dehydrocholate                                    -55.534588
                                                        ...
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})    -0.000002
starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})     -0.000007
sulfate                                               -0.426998
thiosulfate(2-)                                       -0.166330
uracil                                               -20.704723
Name: flux, Length: 388, dtype: float64

In [132]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [133]:
high_fiber_ruminococcus_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Ruminococcus']
high_fiber_ruminococcus_only

,taxon,direction,sample_id,medium,name,flux
1961,Ruminococcus,import,SRR15032094,high_fiber,Glycine,-55.253978
1969,Ruminococcus,import,SRR15032095,high_fiber,Glycine,-67.451611
1991,Ruminococcus,import,SRR15032083,high_fiber,Glycine,-58.896965
1995,Ruminococcus,import,SRR15032082,high_fiber,Glycine,-53.589062
2000,Ruminococcus,import,SRR15032096,high_fiber,Glycine,-59.462865
...,...,...,...,...,...,...
102238,Ruminococcus,import,SRR15032379,high_fiber,thiosulfate(2-),-0.002267
102241,Ruminococcus,import,SRR15032385,high_fiber,thiosulfate(2-),-0.021512
102269,Ruminococcus,import,SRR15032453,high_fiber,thiosulfate(2-),-0.002831
102278,Ruminococcus,import,SRR15032455,high_fiber,thiosulfate(2-),-0.003689
102282,Ruminococcus,import,SRR15032474,high_fiber,thiosulfate(2-),-0.144373

In [134]:
mean_import_of_high_fiber_ruminococcus = high_fiber_ruminococcus_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_ruminococcus

name
(R)-lactate                                                                                                          -75.849324
(S)-lactate                                                                                                          -74.240000
(S)-propane-1,2-diol                                                                                                 -53.671188
12-Dehydrocholate                                                                                                    -59.554308
2-Oxobutanoate                                                                                                       -14.214149
                                                                                                                        ...
potassium                                                                                                             -0.000419
proton                                                                                                               -57.603115
starch n=1200 repeat units (300 repeat units amylose, 900 repeat units amylopectin, corresponds to potatoe starch)    -0.007225
sulfate                                                                                                               -0.181014
thiosulfate(2-)                                                                                                       -0.037623
Name: flux, Length: 87, dtype: float64

In [135]:
western_ruminococcus_imports = pd.DataFrame (mean_import_of_western_ruminococcus, columns = ['flux'])

In [136]:
western_ruminococcus_imports.rename(columns={"flux": "western_flux_ruminococcus"}, inplace=True)

In [137]:
western_ruminococcus_imports

                                                    western_flux_ruminococcus
name
(R)-lactate                                                        -79.871701
(S)-lactate                                                        -78.742605
(S)-propane-1,2-diol                                               -34.347199
1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)                    -0.000001
12-Dehydrocholate                                                  -55.534588
...                                                                       ...
starch, structure 1 (1,6-{7[1,4-Glc], 4[1,4-Glc]})                  -0.000002
starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})                   -0.000007
sulfate                                                             -0.426998
thiosulfate(2-)                                                     -0.166330
uracil                                                             -20.704723

[388 rows x 1 columns]

In [138]:
high_fiber_ruminococcus_imports = pd.DataFrame (mean_import_of_high_fiber_ruminococcus, columns = ['flux'])

In [139]:
high_fiber_ruminococcus_imports.rename(columns={"flux": "high_fiber_flux_ruminococcus"}, inplace=True)

In [140]:
high_fiber_ruminococcus_imports

                                                    high_fiber_flux_ruminococcus
name
(R)-lactate                                                           -75.849324
(S)-lactate                                                           -74.240000
(S)-propane-1,2-diol                                                  -53.671188
12-Dehydrocholate                                                     -59.554308
2-Oxobutanoate                                                        -14.214149
...                                                                          ...
potassium                                                              -0.000419
proton                                                                -57.603115
starch n=1200 repeat units (300 repeat units am...                     -0.007225
sulfate                                                                -0.181014
thiosulfate(2-)                                                        -0.037623

[87 rows x 1 columns]

In [141]:
combined_diet_fluxes_ruminococcus = pd.concat([western_ruminococcus_imports['western_flux_ruminococcus'], high_fiber_ruminococcus_imports['high_fiber_flux_ruminococcus']], axis=1, keys= ['western_ruminococcus_imports', 'high_fiber_ruminococcus_imports'])

In [142]:
combined_diet_fluxes_ruminococcus

,western_ruminococcus_imports,high_fiber_ruminococcus_imports
name,,
(R)-lactate,-79.871701,-75.849324
(S)-lactate,-78.742605,-74.240000
"(S)-propane-1,2-diol",-34.347199,-53.671188
"1,2-Diacyl-sn-glycerol (dioctadecanoyl, n-C18:0)",-0.000001,NaN
12-Dehydrocholate,-55.534588,-59.554308
...,...,...
"starch, structure 2 (1,6-{2[1,4-Glc], [1,4-Glc]})",-0.000007,NaN
sulfate,-0.426998,-0.181014
thiosulfate(2-),-0.166330,-0.037623
uracil,-20.704723,NaN
Glycerol,NaN,-34.510348

In [143]:
ruminococcus_imports_for_both_diets = combined_diet_fluxes_ruminococcus.dropna()

In [144]:
ruminococcus_imports_for_both_diets

,western_ruminococcus_imports,high_fiber_ruminococcus_imports
name,,
(R)-lactate,-79.871701,-75.849324
(S)-lactate,-78.742605,-74.240000
"(S)-propane-1,2-diol",-34.347199,-53.671188
12-Dehydrocholate,-55.534588,-59.554308
2-Oxobutanoate,-14.247240,-14.214149
...,...,...
potassium,-0.001709,-0.000419
proton,-66.528615,-57.603115
"starch n=1200 repeat units (300 repeat units amylose, 900 repeat units amylopectin, corresponds to potatoe starch)",-0.000128,-0.007225
sulfate,-0.426998,-0.181014
thiosulfate(2-),-0.166330,-0.037623

In [145]:
ruminococcus_euclidean_distance = ((ruminococcus_imports_for_both_diets.western_ruminococcus_imports - ruminococcus_imports_for_both_diets.high_fiber_ruminococcus_imports)**2).sum()**(1/2)

ruminococcus_euclidean_distance

46.76183246583985

# Akkermansia

In [146]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [147]:
western_akkermansia_only = western_only.loc[western_only['taxon'] == 'Akkermansia']
western_akkermansia_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
18,Akkermansia,import,SRR15032081,western,released mucin-type O-glycan No 68,-0.000001
41,Akkermansia,import,SRR15032344,western,released mucin-type O-glycan No 68,-0.000001
62,Akkermansia,import,SRR15032081,western,hydrogenphosphate,-0.137294
119,Akkermansia,import,SRR15032099,western,hydrogenphosphate,-0.309431
...,...,...,...,...,...,...
104679,Akkermansia,import,SRR15032324,western,released mucin-type O-glycan No 32,-0.000003
104729,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 138,-0.000001
104750,Akkermansia,import,SRR15032324,western,released mucin-type O-glycan No 173,-0.000003
104759,Akkermansia,import,SRR15032439,western,released mucin-type O-glycan No 173,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001

In [148]:
mean_import_of_western_akkermansia = western_akkermansia_only.groupby('name')["flux"].mean()
mean_import_of_western_akkermansia

name
(S)-propane-1,2-diol                                  -72.412195
Adenosine                                              -0.000004
Alpha-1,3-Galactose-N-acetylgalactosamine              -0.000001
Alpha-2,6-N-acetylneuraminate-N-acetylgalactosamine    -0.000003
Ammonium                                              -27.286958
                                                         ...
released sialyl-Tn antigen                             -0.000003
sialyl-T antigen                                       -0.000002
sialyl-Tn antigen                                      -0.000002
sulfate                                                -0.196022
uracil                                                 -0.013216
Name: flux, Length: 247, dtype: float64

In [149]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [150]:
high_fiber_akkermansia_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Akkermansia']
high_fiber_akkermansia_only

,taxon,direction,sample_id,medium,name,flux
221,Akkermansia,import,SRR15032130,high_fiber,hydrogenphosphate,-0.459514
233,Akkermansia,import,SRR15032141,high_fiber,hydrogenphosphate,-0.407931
283,Akkermansia,import,SRR15032161,high_fiber,hydrogenphosphate,-0.497020
340,Akkermansia,import,SRR15032288,high_fiber,hydrogenphosphate,-0.257341
385,Akkermansia,import,SRR15032290,high_fiber,hydrogenphosphate,-0.219296
...,...,...,...,...,...,...
99293,Akkermansia,import,SRR15032353,high_fiber,O2,-1.545350
102477,Akkermansia,import,SRR15032288,high_fiber,octadecanoate (n-C18:0),-0.006533
102491,Akkermansia,import,SRR15032290,high_fiber,octadecanoate (n-C18:0),-0.005710
102656,Akkermansia,import,SRR15032423,high_fiber,octadecanoate (n-C18:0),-0.005796
102659,Akkermansia,import,SRR15032428,high_fiber,octadecanoate (n-C18:0),-0.013069

In [151]:
mean_import_of_high_fiber_akkermansia = high_fiber_akkermansia_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_akkermansia

name
(S)-propane-1,2-diol            -70.948112
Adenosine                        -0.000001
Ammonium                        -15.552513
Chloride                         -0.000826
Co2+                             -0.000826
Cu2+                             -0.000826
Cytidine                         -0.031032
D-Fructose                       -5.239300
D-Glucosamine                    -4.209554
D-glucose                        -0.096235
Fe2+                             -0.000826
Fe3+                             -0.000826
Glycine                         -38.101644
Hexadecanoate (n-C16:0)          -0.312693
Hydrogen                         -7.145183
Hydrogen sulfide                -10.106159
Indole                           -0.012591
L-asparagine                     -0.053570
L-aspartate(1-)                 -90.277755
L-cysteinylglycine               -0.002508
L-fucose                         -8.830317
L-glutamate(1-)                  -5.171648
L-histidine                      -0.021143
L-leucine                        -0.100133
L-phenylalanine                  -0.027876
L-proline                       -31.902013
L-serine                         -3.323203
L-threonine                     -75.710833
L-tyrosine                       -0.064381
Menaquinone 8                    -0.000826
Mn2+                             -0.000826
N-acetyl-D-galactosamine         -0.000432
N-acetyl-D-glucosamine           -5.016333
N-acetylneuraminate              -3.360959
O2                               -0.752554
Protoheme                        -0.000826
Spermidine                       -0.000826
Succinate                       -13.802546
Thiamin                          -0.000825
Ubiquinone-8                     -0.000826
Water                           -20.619941
Zinc                             -0.000826
acetaldehyde                    -60.724300
acetate                         -16.612541
calcium(2+)                      -0.000826
carbon dioxide                  -84.643348
ethanol                         -83.974809
hydrogenphosphate                -0.441473
laurate                          -8.938050
magnesium                        -0.000826
meso-2,6-Diaminoheptanedioate    -1.013601
octadecanoate (n-C18:0)          -0.007777
potassium                        -0.000826
sulfate                          -0.624982
uracil                           -0.009109
Name: flux, dtype: float64

In [152]:
western_akkermansia_imports = pd.DataFrame (mean_import_of_western_akkermansia, columns = ['flux'])

In [153]:
western_akkermansia_imports.rename(columns={"flux": "western_flux_akkermansia"}, inplace=True)

In [154]:
western_akkermansia_imports

                                                    western_flux_akkermansia
name
(S)-propane-1,2-diol                                              -72.412195
Adenosine                                                          -0.000004
Alpha-1,3-Galactose-N-acetylgalactosamine                          -0.000001
Alpha-2,6-N-acetylneuraminate-N-acetylgalactosa...                 -0.000003
Ammonium                                                          -27.286958
...                                                                      ...
released sialyl-Tn antigen                                         -0.000003
sialyl-T antigen                                                   -0.000002
sialyl-Tn antigen                                                  -0.000002
sulfate                                                            -0.196022
uracil                                                             -0.013216

[247 rows x 1 columns]

In [155]:
high_fiber_akkermansia_imports = pd.DataFrame (mean_import_of_high_fiber_akkermansia, columns = ['flux'])

In [156]:
high_fiber_akkermansia_imports.rename(columns={"flux": "high_fiber_flux_akkermansia"}, inplace=True)

In [157]:
high_fiber_akkermansia_imports

                               high_fiber_flux_akkermansia
name
(S)-propane-1,2-diol                            -70.948112
Adenosine                                        -0.000001
Ammonium                                        -15.552513
Chloride                                         -0.000826
Co2+                                             -0.000826
Cu2+                                             -0.000826
Cytidine                                         -0.031032
D-Fructose                                       -5.239300
D-Glucosamine                                    -4.209554
D-glucose                                        -0.096235
Fe2+                                             -0.000826
Fe3+                                             -0.000826
Glycine                                         -38.101644
Hexadecanoate (n-C16:0)                          -0.312693
Hydrogen                                         -7.145183
Hydrogen sulfide                                -10.106159
Indole                                           -0.012591
L-asparagine                                     -0.053570
L-aspartate(1-)                                 -90.277755
L-cysteinylglycine                               -0.002508
L-fucose                                         -8.830317
L-glutamate(1-)                                  -5.171648
L-histidine                                      -0.021143
L-leucine                                        -0.100133
L-phenylalanine                                  -0.027876
L-proline                                       -31.902013
L-serine                                         -3.323203
L-threonine                                     -75.710833
L-tyrosine                                       -0.064381
Menaquinone 8                                    -0.000826
Mn2+                                             -0.000826
N-acetyl-D-galactosamine                         -0.000432
N-acetyl-D-glucosamine                           -5.016333
N-acetylneuraminate                              -3.360959
O2                                               -0.752554
Protoheme                                        -0.000826
Spermidine                                       -0.000826
Succinate                                       -13.802546
Thiamin                                          -0.000825
Ubiquinone-8                                     -0.000826
Water                                           -20.619941
Zinc                                             -0.000826
acetaldehyde                                    -60.724300
acetate                                         -16.612541
calcium(2+)                                      -0.000826
carbon dioxide                                  -84.643348
ethanol                                         -83.974809
hydrogenphosphate                                -0.441473
laurate                                          -8.938050
magnesium                                        -0.000826
meso-2,6-Diaminoheptanedioate                    -1.013601
octadecanoate (n-C18:0)                          -0.007777
potassium                                        -0.000826
sulfate                                          -0.624982
uracil                                           -0.009109

In [158]:
combined_diet_fluxes_akkermansia = pd.concat([western_akkermansia_imports['western_flux_akkermansia'], high_fiber_akkermansia_imports['high_fiber_flux_akkermansia']], axis=1, keys= ['western_akkermansia_imports', 'high_fiber_akkermansia_imports'])

In [159]:
combined_diet_fluxes_akkermansia

,western_akkermansia_imports,high_fiber_akkermansia_imports
name,,
"(S)-propane-1,2-diol",-72.412195,-70.948112
Adenosine,-0.000004,-0.000001
"Alpha-1,3-Galactose-N-acetylgalactosamine",-0.000001,NaN
"Alpha-2,6-N-acetylneuraminate-N-acetylgalactosamine",-0.000003,NaN
Ammonium,-27.286958,-15.552513
...,...,...
released sialyl-Tn antigen,-0.000003,NaN
sialyl-T antigen,-0.000002,NaN
sialyl-Tn antigen,-0.000002,NaN
sulfate,-0.196022,-0.624982
uracil,-0.013216,-0.009109

In [160]:
akkermansia_imports_for_both_diets = combined_diet_fluxes_akkermansia.dropna()

In [161]:
akkermansia_imports_for_both_diets

,western_akkermansia_imports,high_fiber_akkermansia_imports
name,,
"(S)-propane-1,2-diol",-72.412195,-70.948112
Adenosine,-0.000004,-0.000001
Ammonium,-27.286958,-15.552513
Chloride,-0.000451,-0.000826
Co2+,-0.000451,-0.000826
Cu2+,-0.000451,-0.000826
Cytidine,-0.046708,-0.031032
D-Fructose,-6.403369,-5.239300
D-Glucosamine,-5.039943,-4.209554
D-glucose,-0.134181,-0.096235
Fe2+,-0.000452,-0.000826
Fe3+,-0.000451,-0.000826
Glycine,-50.362016,-38.101644
Hexadecanoate (n-C16:0),-0.102622,-0.312693
Hydrogen,-7.932640,-7.145183
Hydrogen sulfide,-12.109352,-10.106159
Indole,-0.006882,-0.012591
L-asparagine,-0.029279,-0.053570
L-aspartate(1-),-89.864216,-90.277755
L-cysteinylglycine,-0.078959,-0.002508
L-fucose,-3.687175,-8.830317
L-glutamate(1-),-4.383999,-5.171648
L-histidine,-0.011556,-0.021143
L-leucine,-0.040049,-0.100133
L-phenylalanine,-0.019912,-0.027876
L-proline,-27.045172,-31.902013
L-serine,-8.280051,-3.323203
L-threonine,-80.530178,-75.710833
L-tyrosine,-0.030141,-0.064381
Menaquinone 8,-0.000452,-0.000826
Mn2+,-0.000451,-0.000826
N-acetyl-D-galactosamine,-0.000069,-0.000432
N-acetyl-D-glucosamine,-6.047826,-5.016333
N-acetylneuraminate,-4.143576,-3.360959
O2,-0.739859,-0.752554
Protoheme,-0.000451,-0.000826
Spermidine,-0.000453,-0.000826
Succinate,-19.209017,-13.802546
Thiamin,-0.000456,-0.000825
Ubiquinone-8,-0.000452,-0.000826
Water,-20.455297,-20.619941
Zinc,-0.000451,-0.000826
acetaldehyde,-62.422946,-60.724300
acetate,-23.401726,-16.612541
calcium(2+),-0.000451,-0.000826
carbon dioxide,-82.652359,-84.643348
ethanol,-84.779249,-83.974809
hydrogenphosphate,-0.242483,-0.441473
laurate,-10.572231,-8.938050
magnesium,-0.000452,-0.000826
"meso-2,6-Diaminoheptanedioate",-0.646182,-1.013601
octadecanoate (n-C18:0),-0.005321,-0.007777
potassium,-0.000451,-0.000826
sulfate,-0.196022,-0.624982
uracil,-0.013216,-0.009109

In [162]:
akkermansia_euclidean_distance = ((akkermansia_imports_for_both_diets.western_akkermansia_imports - akkermansia_imports_for_both_diets.high_fiber_akkermansia_imports)**2).sum()**(1/2)

akkermansia_euclidean_distance

21.97892630802339

# Paraprevotella

In [163]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [164]:
western_paraprevotella_only = western_only.loc[western_only['taxon'] == 'Paraprevotella']
western_paraprevotella_only

,taxon,direction,sample_id,medium,name,flux
358,Paraprevotella,import,SRR15032287,western,hydrogenphosphate,-0.015989
527,Paraprevotella,import,SRR15032308,western,hydrogenphosphate,-0.128883
2899,Paraprevotella,import,SRR15032195,western,D-Galactose,-0.048843
2959,Paraprevotella,import,SRR15032314,western,D-Galactose,-0.057318
2983,Paraprevotella,import,SRR15032331,western,D-Galactose,-0.022026
...,...,...,...,...,...,...
104373,Paraprevotella,import,SRR15032313,western,4-Aminobenzoate,-0.000894
104374,Paraprevotella,import,SRR15032314,western,4-Aminobenzoate,-0.000935
104375,Paraprevotella,import,SRR15032308,western,4-Aminobenzoate,-0.001208
104376,Paraprevotella,import,SRR15032331,western,4-Aminobenzoate,-0.001220
104377,Paraprevotella,import,SRR15032330,western,4-Aminobenzoate,-0.001089

In [165]:
mean_import_of_western_paraprevotella = western_paraprevotella_only.groupby('name')["flux"].mean()
mean_import_of_western_paraprevotella

name
2-deoxyadenosine                     -15.940884
4-Aminobenzoate                       -0.000866
4-hydroxybenzoate                     -0.000468
AMP                                   -0.203012
Adenosine                            -29.210891
                                        ...
released mucin-type O-glycan No 22    -0.000006
released mucin-type O-glycan No 3     -0.000001
sulfate                               -0.000450
tetradecanoate (n-C14:0)              -0.021832
uracil                               -54.776683
Name: flux, Length: 66, dtype: float64

In [166]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [167]:
high_fiber_paraprevotella_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Paraprevotella']
high_fiber_paraprevotella_only

,taxon,direction,sample_id,medium,name,flux
150,Paraprevotella,import,SRR15032110,high_fiber,hydrogenphosphate,-0.244693
160,Paraprevotella,import,SRR15032119,high_fiber,hydrogenphosphate,-0.042179
172,Paraprevotella,import,SRR15032117,high_fiber,hydrogenphosphate,-0.334265
461,Paraprevotella,import,SRR15032312,high_fiber,hydrogenphosphate,-0.030583
484,Paraprevotella,import,SRR15032321,high_fiber,hydrogenphosphate,-0.229457
...,...,...,...,...,...,...
102563,Paraprevotella,import,SRR15032329,high_fiber,octadecanoate (n-C18:0),-0.056107
102611,Paraprevotella,import,SRR15032372,high_fiber,octadecanoate (n-C18:0),-0.002830
102703,Paraprevotella,import,SRR15032456,high_fiber,octadecanoate (n-C18:0),-0.008641
102705,Paraprevotella,import,SRR15032455,high_fiber,octadecanoate (n-C18:0),-0.015942
102730,Paraprevotella,import,SRR15032494,high_fiber,octadecanoate (n-C18:0),-0.007518

In [168]:
mean_import_of_high_fiber_paraprevotella = high_fiber_paraprevotella_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_paraprevotella

name
2-deoxyadenosine           -23.035010
4-hydroxybenzoate           -0.000804
Adenine                     -7.558186
Adenosine                  -23.061214
Ammonium                   -11.335716
                              ...
potassium                   -0.000804
proton                     -81.691022
sulfate                     -0.000804
tetradecanoate (n-C14:0)    -0.038975
uracil                     -58.973646
Name: flux, Length: 62, dtype: float64

In [169]:
western_paraprevotella_imports = pd.DataFrame (mean_import_of_western_paraprevotella, columns = ['flux'])

In [170]:
western_paraprevotella_imports.rename(columns={"flux": "western_flux_paraprevotella"}, inplace=True)

In [171]:
western_paraprevotella_imports

                                    western_flux_paraprevotella
name
2-deoxyadenosine                                     -15.940884
4-Aminobenzoate                                       -0.000866
4-hydroxybenzoate                                     -0.000468
AMP                                                   -0.203012
Adenosine                                            -29.210891
...                                                         ...
released mucin-type O-glycan No 22                    -0.000006
released mucin-type O-glycan No 3                     -0.000001
sulfate                                               -0.000450
tetradecanoate (n-C14:0)                              -0.021832
uracil                                               -54.776683

[66 rows x 1 columns]

In [172]:
high_fiber_paraprevotella_imports = pd.DataFrame (mean_import_of_high_fiber_paraprevotella, columns = ['flux'])

In [173]:
high_fiber_paraprevotella_imports.rename(columns={"flux": "high_fiber_flux_paraprevotella"}, inplace=True)

In [174]:
high_fiber_paraprevotella_imports

                          high_fiber_flux_paraprevotella
name
2-deoxyadenosine                              -23.035010
4-hydroxybenzoate                              -0.000804
Adenine                                        -7.558186
Adenosine                                     -23.061214
Ammonium                                      -11.335716
...                                                  ...
potassium                                      -0.000804
proton                                        -81.691022
sulfate                                        -0.000804
tetradecanoate (n-C14:0)                       -0.038975
uracil                                        -58.973646

[62 rows x 1 columns]

In [175]:
combined_diet_fluxes_paraprevotella = pd.concat([western_paraprevotella_imports['western_flux_paraprevotella'], high_fiber_paraprevotella_imports['high_fiber_flux_paraprevotella']], axis=1, keys= ['western_paraprevotella_imports', 'high_fiber_paraprevotella_imports'])

In [176]:
combined_diet_fluxes_paraprevotella

,western_paraprevotella_imports,high_fiber_paraprevotella_imports
name,,
2-deoxyadenosine,-15.940884,-23.035010
4-Aminobenzoate,-0.000866,NaN
4-hydroxybenzoate,-0.000468,-0.000804
AMP,-0.203012,NaN
Adenosine,-29.210891,-23.061214
...,...,...
L-valine,NaN,-0.043497
O2,NaN,-0.000113
Riboflavin,NaN,-0.001263
Thymidine,NaN,-0.002537
chorismate,NaN,-0.083587

In [177]:
paraprevotella_imports_for_both_diets = combined_diet_fluxes_paraprevotella.dropna()

In [178]:
paraprevotella_imports_for_both_diets

,western_paraprevotella_imports,high_fiber_paraprevotella_imports
name,,
2-deoxyadenosine,-15.940884,-23.035010
4-hydroxybenzoate,-0.000468,-0.000804
Adenosine,-29.210891,-23.061214
Ammonium,-10.140805,-11.335716
Chloride,-0.000450,-0.000804
Citrate,-45.074534,-38.879291
Co2+,-0.000450,-0.000804
Cu2+,-0.000450,-0.000804
Cytidine,-45.174282,-6.229609
D-glucose,-0.019727,-0.024099
D-glucuronate,-0.000873,-0.001509
Deoxyguanosine,-16.731900,-14.956636
Fe2+,-0.000571,-0.001149
Fe3+,-0.000413,-0.001380
Glycerol,-17.593920,-18.411577
Guanine,-33.021703,-27.561451
Inosine,-13.975398,-15.561849
L-alanine,-0.073172,-0.130629
L-asparagine,-20.142935,-23.514413
L-aspartate(1-),-79.536685,-81.696503
L-cysteinylglycine,-0.006522,-0.010229
L-fucose,-12.075688,-16.434108
L-glutamate(1-),-29.142703,-23.332489
L-glutamine,-13.758310,-14.901524
L-methionine,-0.024502,-0.050263
L-phenylalanine,-0.017200,-0.038370
L-threonine,-42.584992,-36.481785
Maltose,-0.002756,-0.031642
Menaquinone 8,-0.000221,-0.000876
Mn2+,-0.000450,-0.000804
Nicotinamide,-3.211402,-1.240513
Nicotinate,-2.200344,-2.694991
Protoheme,-0.000450,-0.000804
Reduced glutathione,-0.000450,-0.000804
Siroheme,-0.000450,-0.000804
Spermidine,-0.000450,-0.000804
Thiamin,-0.000450,-0.000804
Urea,-8.113605,-7.047532
Uridine,-30.554630,-28.759788
Water,-24.116119,-27.303574
Xanthine,-6.712875,-10.806284
Zinc,-0.000450,-0.000804
acetaldehyde,-24.762451,-39.846483
acetate,-2.085388,-14.355037
calcium(2+),-0.000450,-0.000804
hydrogenphosphate,-0.072436,-0.210836
magnesium,-0.000450,-0.000804
"meso-2,6-Diaminoheptanedioate",-1.228526,-1.188592
octadecanoate (n-C18:0),-0.012387,-0.022124
potassium,-0.000450,-0.000804
proton,-77.750909,-81.691022
sulfate,-0.000450,-0.000804
tetradecanoate (n-C14:0),-0.021832,-0.038975
uracil,-54.776683,-58.973646

In [179]:
paraprevotella_euclidean_distance = ((paraprevotella_imports_for_both_diets.western_paraprevotella_imports - paraprevotella_imports_for_both_diets.high_fiber_paraprevotella_imports)**2).sum()**(1/2)

paraprevotella_euclidean_distance

47.27341328355365

# Megamonas

In [180]:
western_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'western']
western_only

,taxon,direction,sample_id,medium,name,flux
0,Akkermansia,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
1,Eubacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000003
2,Faecalibacterium,import,SRR15032081,western,mucin-type O-glycan No 144,-0.000001
3,Bifidobacterium,import,SRR15032099,western,mucin-type O-glycan No 144,-0.000002
4,Bacteroides,import,SRR15032282,western,mucin-type O-glycan No 144,-0.000004
...,...,...,...,...,...,...
104834,Bacteroides,import,SRR15032344,western,mucin-type O-glycan No 135,-0.000001
104835,Akkermansia,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000001
104836,Bacteroides,import,SRR15032439,western,mucin-type O-glycan No 135,-0.000008
104838,Bacteroides,import,SRR15032392,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000049
104839,Parabacteroides,import,SRR15032439,western,"laminarin (n=30 repeat units, beta -1,3 glc)",-0.000006

In [181]:
western_megamonas_only = western_only.loc[western_only['taxon'] == 'Megamonas']
western_megamonas_only

Empty DataFrame
Columns: [taxon, direction, sample_id, medium, name, flux]
Index: []

In [182]:
mean_import_of_western_megamonas = western_megamonas_only.groupby('name')["flux"].mean()
mean_import_of_western_megamonas

Series([], Name: flux, dtype: float64)

In [183]:
high_fiber_only = taxon_imports_table.loc[taxon_imports_table['medium'] == 'high_fiber']
high_fiber_only

,taxon,direction,sample_id,medium,name,flux
68,Bacteroides,import,SRR15032094,high_fiber,hydrogenphosphate,-27.456853
69,Blautia,import,SRR15032094,high_fiber,hydrogenphosphate,-11.983896
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
76,Bacteroides,import,SRR15032095,high_fiber,hydrogenphosphate,-2.522117
77,Blautia,import,SRR15032095,high_fiber,hydrogenphosphate,-10.552848
...,...,...,...,...,...,...
104355,Bacteroides,import,SRR15032479,high_fiber,3-Dehydrochenodeoxycholate,-0.422812
104357,Bacteroides,import,SRR15032489,high_fiber,3-Dehydrochenodeoxycholate,-0.165069
104363,Bacteroides,import,SRR15032503,high_fiber,3-Dehydrochenodeoxycholate,-0.202800
104391,Sutterella,import,SRR15032310,high_fiber,trimethylamine,-9.052821
104396,Desulfovibrio,import,SRR15032511,high_fiber,trimethylamine,-3.537798

In [184]:
high_fiber_megamonas_only = high_fiber_only.loc[high_fiber_only['taxon'] == 'Megamonas']
high_fiber_megamonas_only

,taxon,direction,sample_id,medium,name,flux
70,Megamonas,import,SRR15032094,high_fiber,hydrogenphosphate,-0.066602
98,Megamonas,import,SRR15032079,high_fiber,hydrogenphosphate,-0.096595
117,Megamonas,import,SRR15032103,high_fiber,hydrogenphosphate,-0.042782
729,Megamonas,import,SRR15032404,high_fiber,hydrogenphosphate,-0.073747
973,Megamonas,import,SRR15032487,high_fiber,hydrogenphosphate,-0.050973
...,...,...,...,...,...,...
101108,Megamonas,import,SRR15032079,high_fiber,(S)-malate(2-),-71.033700
101109,Megamonas,import,SRR15032103,high_fiber,(S)-malate(2-),-62.980349
101166,Megamonas,import,SRR15032404,high_fiber,(S)-malate(2-),-65.774984
101181,Megamonas,import,SRR15032487,high_fiber,(S)-malate(2-),-63.751716
101203,Megamonas,import,SRR15032079,high_fiber,Thymidine,-0.000620

In [185]:
mean_import_of_high_fiber_megamonas = high_fiber_megamonas_only.groupby('name')["flux"].mean()
mean_import_of_high_fiber_megamonas

name
(S)-lactate                -14.270235
(S)-malate(2-)             -65.332070
2-Demethylmenaquinone 8     -0.000103
2-deoxyadenosine           -13.444643
Adenine                    -35.077348
                              ...
potassium                   -0.000363
proton                      -9.075639
sulfate                     -0.000363
tetradecanoate (n-C14:0)    -0.000915
uracil                     -23.836852
Name: flux, Length: 63, dtype: float64

In [186]:
western_megamonas_imports = pd.DataFrame (mean_import_of_western_megamonas, columns = ['flux'])

In [187]:
western_megamonas_imports.rename(columns={"flux": "western_flux_megamonas"}, inplace=True)

In [188]:
western_megamonas_imports

Empty DataFrame
Columns: [western_flux_megamonas]
Index: []

In [189]:
high_fiber_megamonas_imports = pd.DataFrame (mean_import_of_high_fiber_megamonas, columns = ['flux'])

In [190]:
high_fiber_megamonas_imports.rename(columns={"flux": "high_fiber_flux_megamonas"}, inplace=True)

In [191]:
high_fiber_megamonas_imports

                          high_fiber_flux_megamonas
name
(S)-lactate                              -14.270235
(S)-malate(2-)                           -65.332070
2-Demethylmenaquinone 8                   -0.000103
2-deoxyadenosine                         -13.444643
Adenine                                  -35.077348
...                                             ...
potassium                                 -0.000363
proton                                    -9.075639
sulfate                                   -0.000363
tetradecanoate (n-C14:0)                  -0.000915
uracil                                   -23.836852

[63 rows x 1 columns]

In [192]:
combined_diet_fluxes_megamonas = pd.concat([western_megamonas_imports['western_flux_megamonas'], high_fiber_megamonas_imports['high_fiber_flux_megamonas']], axis=1, keys= ['western_megamonas_imports', 'high_fiber_megamonas_imports'])

In [193]:
combined_diet_fluxes_megamonas

,western_megamonas_imports,high_fiber_megamonas_imports
name,,
(S)-lactate,NaN,-14.270235
(S)-malate(2-),NaN,-65.332070
2-Demethylmenaquinone 8,NaN,-0.000103
2-deoxyadenosine,NaN,-13.444643
Adenine,NaN,-35.077348
...,...,...
potassium,NaN,-0.000363
proton,NaN,-9.075639
sulfate,NaN,-0.000363
tetradecanoate (n-C14:0),NaN,-0.000915
uracil,NaN,-23.836852

In [194]:
megamonas_imports_for_both_diets = combined_diet_fluxes_megamonas.dropna()

In [195]:
megamonas_imports_for_both_diets

Empty DataFrame
Columns: [western_megamonas_imports, high_fiber_megamonas_imports]
Index: []

In [197]:
megamonas_euclidean_distance = ((megamonas_imports_for_both_diets.western_megamonas_imports - megamonas_imports_for_both_diets.high_fiber_megamonas_imports)**2).sum()**(1/2)

megamonas_euclidean_distance

0.0

# all the euclidean distances

In [198]:
bacteroides_euclidean_distance

63.35243012853294

In [199]:
prevotella_euclidean_distance

64.56405495878849

In [200]:
faecalibacterium_euclidean_distance

48.68283693595469

In [201]:
roseburia_euclidean_distance

27.39142994145541

In [202]:
blautia_euclidean_distance

28.36475275549472

In [203]:
alistipes_euclidean_distance

51.161930368231786

In [204]:
ruminococcus_euclidean_distance

46.76183246583985

In [205]:
akkermansia_euclidean_distance

21.97892630802339

In [207]:
paraprevotella_euclidean_distance

47.27341328355365